// apps/frontend/atoma-components-solid/components/card/index.tsx
import { AsProps } from "solid-styled-components";
import { Wrapper } from "./styles";
import { children as createChildren, type Component, type JSX } from "solid-js";

export type CardProps = JSX.HTMLAttributes<HTMLDivElement> &
	AsProps & {
		children: JSX.Element | JSX.Element[];
	};

export const Card: Component<CardProps> = (props) => {
	const { children, ...rest } = props;
	const c = createChildren(() => props.children);

	return <Wrapper {...rest}>{c()}</Wrapper>;
};

export default Card;

// apps/frontend/atoma-components/components/card/index.tsx
import React from "react";
import { Wrapper } from "./styles";

export type CardProps = React.HTMLAttributes<HTMLDivElement> & {
	children: React.ReactNode | React.ReactNode[];
};

export const Card: React.FC<CardProps> = (props) => {
	const { children, ...rest } = props;

	return <Wrapper {...rest}>{children}</Wrapper>;
};

export default Card;
